# Site settings
author: Aleksandar Vuk
title: Adventures in Programming
header-img: img/home-bg.png
email: alekvuka@gmail.com
copyright_name: Aleksandar Vuk
description: > # this means to ignore newlines until "baseurl:"
  Learning Ruby and Beyond!  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  alekvuka

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
